In [1]:
import numpy as np
import matplotlib.pyplot as plt
from csci3202.classifiers.cnn import *
from csci3202.data_utils import get_CIFAR10_data
from csci3202.gradient_check import eval_numerical_gradient_array, eval_numerical_gradient
from csci3202.layers import *
from csci3202.fast_layers import *
from csci3202.solver import Solver
a=np.array([1,2,3])

In [4]:
np.zeros((2,)).shape

(2,)

In [21]:
np.tile(a,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [22]:
num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3

input_size = num_inputs * np.prod(input_shape)
weight_size = output_dim * np.prod(input_shape)

x = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)
w = np.linspace(-0.2, 0.3, num=weight_size).reshape(np.prod(input_shape), output_dim)
b = np.linspace(-0.3, 0.1, num=output_dim)

In [23]:
D=np.prod(x.shape[1:])
N=x.shape[0]
x1 = np.reshape(x,(N,D))
b1 = np.tile(b,(N,1))
out = np.matmul(x1,w)+b1

In [24]:
x = np.random.randn(10, 2, 3)
w = np.random.randn(6, 5)
b = np.random.randn(5)
dout = np.random.randn(10, 5)

dx_num = eval_numerical_gradient_array(lambda x: affine_forward(x, w, b)[0], x, dout)
dw_num = eval_numerical_gradient_array(lambda w: affine_forward(x, w, b)[0], w, dout)
db_num = eval_numerical_gradient_array(lambda b: affine_forward(x, w, b)[0], b, dout)

In [25]:
np.shape(w)

(6, 5)

In [26]:
N = x.shape[0]
D=np.prod(x.shape[1:])
x1=np.reshape(x,(N,D))
tmpd=np.matmul(dout,np.transpose(w))
np.reshape(tmpd, np.shape(x))

array([[[-2.43134807,  3.08145094,  1.72177306],
        [-0.32872851,  0.97151829,  2.32276575]],

       [[ 4.98569366, -9.63427643, -6.44595092],
        [-2.0256359 ,  0.57616687, -1.33709038]],

       [[ 4.21506201, -0.62831986, -0.54168643],
        [ 2.27067728, -2.10178714, -1.16738617]],

       [[ 3.06193934, -0.45624751,  0.30382439],
        [-1.02263593,  2.76065424, -2.5372805 ]],

       [[-1.14285144,  1.22317136, -0.70269389],
        [ 0.65955695, -2.2678478 ,  2.87248462]],

       [[ 2.92411417,  1.12485136, -0.76150183],
        [-0.79900872,  2.00032583,  3.56142613]],

       [[ 1.99257152, -2.41593512, -1.47061004],
        [ 0.58211068, -1.24790842, -1.48295522]],

       [[ 1.17600152, -0.76128007,  3.30175276],
        [ 1.79307632,  0.01719775, -9.7697567 ]],

       [[ 3.30313725, -0.11969696, -0.55436289],
        [-0.01318765, -0.14986629, -2.68311118]],

       [[ 2.06854508,  1.76237207, -0.66551127],
        [-0.7134179 ,  0.98617627,  2.8819401 ]]])

In [27]:
np.sum(dout,axis=0).shape

(5,)

In [37]:
x = np.linspace(-0.5, 0.5, num=12).reshape(3, 4)

In [38]:
p=x.copy()

In [39]:
p[p<0]=0

In [40]:
x

array([[-0.5       , -0.40909091, -0.31818182, -0.22727273],
       [-0.13636364, -0.04545455,  0.04545455,  0.13636364],
       [ 0.22727273,  0.31818182,  0.40909091,  0.5       ]])

In [41]:
p

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.04545455, 0.13636364],
       [0.22727273, 0.31818182, 0.40909091, 0.5       ]])

In [50]:
x=np.pad(x,((0,1),(0,0)))

In [73]:
x_shape = (2, 3, 4, 4)
w_shape = (3, 3, 4, 4)
x = np.linspace(-0.1, 0.5, num=np.prod(x_shape)).reshape(x_shape)
w = np.linspace(-0.2, 0.3, num=np.prod(w_shape)).reshape(w_shape)
b = np.linspace(-0.1, 0.2, num=3)

conv_param = {'stride': 2, 'pad': 1}

In [74]:
def rel_error(x, y):
  """ returns relative error """
  return np.max(np.abs(x - y) / (np.maximum(1e-8, np.abs(x) + np.abs(y))))

In [75]:
N,C,H,W = x.shape
F,C,HH,WW = w.shape
  
pad = conv_param['pad']
stride = conv_param['stride']

H_out = 1+(H+2*pad-HH)//stride
W_out = 1+(W+2*pad-WW)//stride

out = np.zeros((N,F,H_out,W_out))
x_padded = np.pad(x,((0,0),(0,0),(pad,pad),(pad,pad)))
for n in range(N):
    for wi in range(W_out):
        for h in range(H_out):
            x_tmp = x_padded[n,:,h*stride:h*stride+HH,wi*stride:wi*stride+WW]
            for f in range(F):
                out[n,f,h,wi]=np.sum(x_tmp*w[f,:,:,:])+b[f]

In [76]:
out

array([[[[-0.08759809, -0.10987781],
         [-0.18387192, -0.2109216 ]],

        [[ 0.21027089,  0.21661097],
         [ 0.22847626,  0.23004637]],

        [[ 0.50813986,  0.54309974],
         [ 0.64082444,  0.67101435]]],


       [[[-0.98053589, -1.03143541],
         [-1.19128892, -1.24695841]],

        [[ 0.69108355,  0.66880383],
         [ 0.59480972,  0.56776003]],

        [[ 2.36270298,  2.36904306],
         [ 2.38090835,  2.38247847]]]])

In [77]:
correct_out = np.array([[[[[-0.08759809, -0.10987781],
                           [-0.18387192, -0.2109216 ]],
                          [[ 0.21027089,  0.21661097],
                           [ 0.22847626,  0.23004637]],
                          [[ 0.50813986,  0.54309974],
                           [ 0.64082444,  0.67101435]]],
                         [[[-0.98053589, -1.03143541],
                           [-1.19128892, -1.24695841]],
                          [[ 0.69108355,  0.66880383],
                           [ 0.59480972,  0.56776003]],
                          [[ 2.36270298,  2.36904306],
                           [ 2.38090835,  2.38247847]]]]])

# Compare your output to ours; difference should be around 1e-8
print('Testing conv_forward_naive')
print('difference: ', rel_error(out, correct_out))

Testing conv_forward_naive
difference:  2.2121476417505994e-08
